//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportData_InExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelData_Import
    {
        public int Id { get; set; }
        public string first_name { get; set; }
        public string Last_name { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string ip_address { get; set; }
    }
}
