//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportData_InExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_inventory_Upload
    {
        public int InventoryId { get; set; }
        public string vendor_id { get; set; }
        public string Item_Code { get; set; }
        public string Item_Name { get; set; }
        public string Unit_Of_Measurement { get; set; }
        public string Item_Type { get; set; }
        public Nullable<int> Closing_Stock { get; set; }
        public System.DateTime UploadDate { get; set; }
    }
}
